import argparse
import json
import os
from typing import Any, Dict, List

from dotenv import load_dotenv
from openai import OpenAI
from tqdm import tqdm


FEATURE_PROMPT = """
作为AI模型，你的任务是处理刑事案件的输入。输入将包括一个刑事案件的描述文本和被告人姓名。请从描述中提取关键词，并将它们分类到以下四个类别：被告基本信息、犯罪行为、犯罪对象特征、主观及悔罪表现。输出必须是一个JSON对象，且只包含JSON，没有任何额外的文本、解释或错误消息。

注意事项:
- 关键词需要围绕被告罪名展开。

关键词解释：
- 被告基本信息：提取与被告人相关的法律特征，如年龄阶段（例如“未成年人”、“成年人”）、前科情况（例如“有前科”、“无前科”）、职业类别（例如“国家工作人员”、“非国家工作人员”），避免具体年龄数字、具体工作单位名称。被告人姓名不重要。
- 犯罪行为：提取犯罪行为的法律类型和重要方式，如“盗窃”、“抢劫”、“故意伤害”，仅提取有法律意义的方式（如“持械”、“入户”），避免具体时间、地点细节。
- 犯罪对象特征：提取犯罪对象的类型特征，如财物性质（例如“公共财产”、“私人财产”）、地点类型（例如“公共场所”、“住宅”），避免具体地名、具体金额数字（可概括为“数额较大”等）。
- 主观及悔罪表现：提取主观意图和悔罪表现的法律描述，如“直接故意”、“过失”、“自首”、“立功”。

JSON格式要求：
- 使用双引号包围键和字符串值。
- 每个键对应一个类别，值是一个字符串数组，包含从描述中提取的关键词（如果某个类别没有关键词，使用空数组 `[]`）。
- 键名必须为： "defendant_info"、"criminal_acts"、"victim_property_details"、"intent_remorse"。

输出示例（仅供参考，实际输出应基于输入内容）：
{
"defendant_info": ["成年人", "有前科", "国家工作人员"],
"criminal_acts": ["盗窃", "入户"],
"victim_property_details": ["私人住宅", "数额较大"],
"intent_remorse": ["直接故意", "自首"]
}

请确保只输出JSON对象。
现在请你处理以下案件：
被告人姓名：{name}
罪名：{crime}
案件事实：{fact}
""".strip()


EMPTY_FEATURES = {
    "defendant_info": [],
    "criminal_acts": [],
    "victim_property_details": [],
    "intent_remorse": [],
}


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: str, data: Any) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def parse_features(raw: str) -> Dict[str, List[str]]:
    first = raw.find("{")
    last = raw.rfind("}")
    if first == -1 or last == -1 or last < first:
        return dict(EMPTY_FEATURES)
    payload = raw[first : last + 1]
    try:
        data = json.loads(payload)
    except json.JSONDecodeError:
        return dict(EMPTY_FEATURES)

    normalized = {}
    for key in EMPTY_FEATURES:
        value = data.get(key, [])
        if isinstance(value, list):
            normalized[key] = [str(x).strip() for x in value if str(x).strip()]
        else:
            normalized[key] = []
    return normalized


def call_llm(client: OpenAI, model: str, prompt: str, max_tokens: int) -> str:
    resp = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=max_tokens,
        stream=False,
    )
    return (resp.choices[0].message.content or "").strip()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate features for cases_with_feature.json with LLM."
    )
    parser.add_argument(
        "--input",
        type=str,
        required=True,
        help="Input case json (generated by prepare_cail_data.py).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="./datas/cases_with_feature.json",
        help="Output path for cases with features.",
    )
    parser.add_argument(
        "--dotenv-path",
        type=str,
        default=".env",
        help="Path to .env file for feature extraction model settings.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="",
        help="LLM model name (optional, overrides .env).",
    )
    parser.add_argument(
        "--base-url",
        type=str,
        default="",
        help="OpenAI-compatible API base URL (optional, overrides .env).",
    )
    parser.add_argument(
        "--api-key",
        type=str,
        default="",
        help="API key (optional, overrides .env/env vars).",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=-1,
        help="Max output tokens (optional, overrides .env).",
    )
    args = parser.parse_args()

    load_dotenv(dotenv_path=args.dotenv_path)

    model_name = (
        args.model
        or os.getenv("case_features_model")
        or os.getenv("CASE_FEATURES_MODEL")
        or "deepseek-chat"
    )
    base_url = (
        args.base_url
        or os.getenv("case_features_base_url")
        or os.getenv("CASE_FEATURES_BASE_URL")
        or "https://api.deepseek.com/v1"
    )
    max_tokens = (
        args.max_tokens
        if args.max_tokens > 0
        else int(
            os.getenv("case_features_max_tokens")
            or os.getenv("CASE_FEATURES_MAX_TOKENS")
            or 1024
        )
    )
    api_key = (
        args.api_key
        or os.getenv("case_features_api_key")
        or os.getenv("CASE_FEATURES_API_KEY")
        or os.getenv("DEEPSEEK_API_KEY")
        or os.getenv("OPENAI_API_KEY")
        or os.getenv("api_key")
    )
    if not api_key:
        raise ValueError("API key is required. Use --api-key or set env vars.")

    cases = load_json(args.input)
    client = OpenAI(api_key=api_key, base_url=base_url)

    output_cases = []
    for case in tqdm(cases, desc="Extracting case features"):
        prompt = FEATURE_PROMPT.format(
            name=case.get("name", ""),
            crime=case.get("crime", []),
            fact=case.get("fact", ""),
        )
        response = call_llm(client, model_name, prompt, max_tokens=max_tokens)
        features = parse_features(response)
        row = dict(case)
        row["features"] = features
        output_cases.append(row)

    write_json(args.output, output_cases)
    print(f"Input cases: {len(cases)}")
    print(f"LLM model: {model_name}")
    print(f"LLM base_url: {base_url}")
    print(f"Output: {args.output}")


if __name__ == "__main__":
    main()
